server {
    listen 80;
    server_name localhost;

    # 开启 gzip
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/javascript application/json application/javascript application/x-javascript application/xml;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 支持 Vue Router 的 History 模式
        try_files $uri $uri/ /index.html;
    }

    # API反向代理 (如果需要)
    location /api/ {
        proxy_pass http://180.76.238.46:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
